name: release-test-build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Simplified Windows CPU generation step for test build
  generate-windows-cpu:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Version
        shell: bash
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
      - run: go get ./...
      - name: go generate
        run: |
          $gopath=(get-command go).source | split-path -parent
          & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\Launch-VsDevShell.ps1"
          cd $env:GITHUB_WORKSPACE
          $env:CMAKE_SYSTEM_VERSION="10.0.22621.0"
          $env:PATH="$gopath;$env:PATH"
          go generate -x ./...
      - uses: actions/upload-artifact@v4
        with:
          name: generate-windows-cpu
          path: llm/llama.cpp/build/**/lib/*

  # Final build for Windows assets without signing
  build-windows:
    runs-on: windows-latest
    needs: [generate-windows-cpu]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set Version
        shell: bash
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
      - run: go get ./...
      - uses: actions/download-artifact@v4
        with:
          name: generate-windows-cpu
          path: llm/llama.cpp/build
      - run: dir llm/llama.cpp/build
      - run: |
          $gopath=(get-command go).source | split-path -parent
          & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\Launch-VsDevShell.ps1"
          cd $env:GITHUB_WORKSPACE
          $env:CMAKE_SYSTEM_VERSION="10.0.22621.0"
          $env:PATH="$gopath;$env:PATH"
          $env:OLLAMA_SKIP_GENERATE="1"
          & .\scripts\build_windows.ps1
      - uses: actions/upload-artifact@v4
        with:
          name: dist-windows
          path: dist/*.exe