name: release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Simplified for brevity, focusing on the Windows build adjustments for test versions.

  # Windows builds modified for test version without signing keys
  build-windows:
    environment: release
    runs-on: windows-latest # Updated for clarity
    needs: [generate-windows-cuda, generate-windows-rocm, generate-windows-cpu]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set Version
        shell: bash
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
      - run: go get
      - uses: actions/download-artifact@v4
        with:
          name: generate-windows-cpu
          path: llm/llama.cpp/build
      - uses: actions/download-artifact@v4
        with:
          name: generate-windows-cuda
          path: llm/llama.cpp/build
      - uses: actions/download-artifact@v4
        with:
          name: windows-cuda-deps
          path: dist/deps
      - uses: actions/download-artifact@v4
        with:
          name: windows-rocm-deps
          path: dist/deps
      - uses: actions/download-artifact@v4
        with:
          name: generate-windows-rocm
          path: llm/llama.cpp/build
      - run: dir llm/llama.cpp/build
      - run: |
          $gopath=(get-command go).source | split-path -parent
          & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\Launch-VsDevShell.ps1"
          cd $env:GITHUB_WORKSPACE
          $env:CMAKE_SYSTEM_VERSION="10.0.22621.0"
          $env:PATH="$gopath;$env:PATH"
          $env:OLLAMA_SKIP_GENERATE="1"
          $env:NVIDIA_DIR=$(resolve-path ".\dist\deps")
          $env:HIP_PATH=$(resolve-path ".\dist\deps")
          & .\scripts\build_windows.ps1
      - uses: actions/upload-artifact@v4
        with:
          name: dist-windows
          path: dist/*.exe

  # Other jobs (like build-darwin, build-linux-amd64, etc.) remain as is.
