name: Full Test Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      
      - name: Install Dependencies
        run: |
          # Example: Install Windows SDK for signtool, if needed
          choco install windows-sdk-10.1 -y
          # Add commands here to install any other dependencies required for your project

      - name: Prepare Environment
        run: |
          # Set up any environment variables or paths needed for the build
          # Example for CUDA, adjust as per actual requirements
          $cudaInstallPath = "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin"
          echo "CUDA_PATH=$cudaInstallPath" | Out-File -Append -FilePath $env:GITHUB_ENV
          echo "$cudaInstallPath" | Out-File -Append -FilePath $env:GITHUB_PATH

      - name: Build Executable
        run: |
          go build -o myapp.exe ./...
          # Adjust the build command as necessary for your project

      - name: Upload EXE as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: myapp.exe
